// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: agent.proto

package go_sapaude_dogai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentType Agent类型枚举
type AgentType int32

const (
	AgentType_AGENT_TYPE_UNSPECIFIED AgentType = 0 // 未指定
	AgentType_AGENT_TYPE_REACT       AgentType = 1 // ReAct Agent
)

// Enum value maps for AgentType.
var (
	AgentType_name = map[int32]string{
		0: "AGENT_TYPE_UNSPECIFIED",
		1: "AGENT_TYPE_REACT",
	}
	AgentType_value = map[string]int32{
		"AGENT_TYPE_UNSPECIFIED": 0,
		"AGENT_TYPE_REACT":       1,
	}
)

func (x AgentType) Enum() *AgentType {
	p := new(AgentType)
	*p = x
	return p
}

func (x AgentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (AgentType) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x AgentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentType.Descriptor instead.
func (AgentType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

// Agent ReAct Agent配置
type Agent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                   // 主键ID
	AgentId         string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                           // Agent唯一标识(eg. agent_0x1234)
	AgentName       string                 `protobuf:"bytes,3,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`                     // Agent名称
	AgentType       string                 `protobuf:"bytes,4,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`                     // Agent类型(ReAct)
	Description     string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                                  // Agent描述
	UsingProviderId string                 `protobuf:"bytes,6,opt,name=using_provider_id,json=usingProviderId,proto3" json:"using_provider_id,omitempty"` // 使用的Provider ID
	UsingModel      string                 `protobuf:"bytes,7,opt,name=using_model,json=usingModel,proto3" json:"using_model,omitempty"`                  // 使用的模型
	// Prompt配置
	SysPrompt string `protobuf:"bytes,8,opt,name=sys_prompt,json=sysPrompt,proto3" json:"sys_prompt,omitempty"` // 系统提示词
	AiPrompt  string `protobuf:"bytes,9,opt,name=ai_prompt,json=aiPrompt,proto3" json:"ai_prompt,omitempty"`    // AI助手提示词
	// Model参数配置
	Model       string  `protobuf:"bytes,10,opt,name=model,proto3" json:"model,omitempty"`                           // 模型名称
	Temperature float64 `protobuf:"fixed64,11,opt,name=temperature,proto3" json:"temperature,omitempty"`             // 温度参数(0.0-1.0)
	MaxTokens   int32   `protobuf:"varint,12,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"` // 最大token数
	TopP        float64 `protobuf:"fixed64,13,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`               // Top P参数
	TopK        int32   `protobuf:"varint,14,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`                // Top K参数
	// 时间戳
	CreatedAt     string `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间
	UpdatedAt     string `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Agent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Agent) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *Agent) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *Agent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Agent) GetUsingProviderId() string {
	if x != nil {
		return x.UsingProviderId
	}
	return ""
}

func (x *Agent) GetUsingModel() string {
	if x != nil {
		return x.UsingModel
	}
	return ""
}

func (x *Agent) GetSysPrompt() string {
	if x != nil {
		return x.SysPrompt
	}
	return ""
}

func (x *Agent) GetAiPrompt() string {
	if x != nil {
		return x.AiPrompt
	}
	return ""
}

func (x *Agent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Agent) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *Agent) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *Agent) GetTopP() float64 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *Agent) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *Agent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Agent) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// CondAgent Agent查询条件
type CondAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Agent唯一标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CondAgent) Reset() {
	*x = CondAgent{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CondAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CondAgent) ProtoMessage() {}

func (x *CondAgent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CondAgent.ProtoReflect.Descriptor instead.
func (*CondAgent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *CondAgent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// SaveAgentReq 保存Agent请求
type SaveAgentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveAgentReq) Reset() {
	*x = SaveAgentReq{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAgentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAgentReq) ProtoMessage() {}

func (x *SaveAgentReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAgentReq.ProtoReflect.Descriptor instead.
func (*SaveAgentReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *SaveAgentReq) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

// SaveAgentRsp 保存Agent响应
type SaveAgentRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveAgentRsp) Reset() {
	*x = SaveAgentRsp{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAgentRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAgentRsp) ProtoMessage() {}

func (x *SaveAgentRsp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAgentRsp.ProtoReflect.Descriptor instead.
func (*SaveAgentRsp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

// UpdateAgentReq 更新Agent请求
type UpdateAgentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Agent唯一标识
	Agent         *Agent                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`                    // 更新的Agent信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentReq) Reset() {
	*x = UpdateAgentReq{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentReq) ProtoMessage() {}

func (x *UpdateAgentReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentReq.ProtoReflect.Descriptor instead.
func (*UpdateAgentReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAgentReq) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UpdateAgentReq) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

// UpdateAgentRsp 更新Agent响应
type UpdateAgentRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentRsp) Reset() {
	*x = UpdateAgentRsp{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentRsp) ProtoMessage() {}

func (x *UpdateAgentRsp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentRsp.ProtoReflect.Descriptor instead.
func (*UpdateAgentRsp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

// GetAgentListsReq 查询Agent列表请求
type GetAgentListsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Condition     *CondAgent             `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"` // 查询条件(可选)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentListsReq) Reset() {
	*x = GetAgentListsReq{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentListsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentListsReq) ProtoMessage() {}

func (x *GetAgentListsReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentListsReq.ProtoReflect.Descriptor instead.
func (*GetAgentListsReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *GetAgentListsReq) GetCondition() *CondAgent {
	if x != nil {
		return x.Condition
	}
	return nil
}

// GetAgentListsRsp 查询Agent列表响应
type GetAgentListsRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentListsRsp) Reset() {
	*x = GetAgentListsRsp{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentListsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentListsRsp) ProtoMessage() {}

func (x *GetAgentListsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentListsRsp.ProtoReflect.Descriptor instead.
func (*GetAgentListsRsp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *GetAgentListsRsp) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

// GetAgentReq 获取指定Agent请求
type GetAgentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Agent唯一标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentReq) Reset() {
	*x = GetAgentReq{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentReq) ProtoMessage() {}

func (x *GetAgentReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentReq.ProtoReflect.Descriptor instead.
func (*GetAgentReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *GetAgentReq) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// GetAgentRsp 获取指定Agent响应
type GetAgentRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRsp) Reset() {
	*x = GetAgentRsp{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRsp) ProtoMessage() {}

func (x *GetAgentRsp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRsp.ProtoReflect.Descriptor instead.
func (*GetAgentRsp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *GetAgentRsp) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

// DeleteAgentsReq 删除Agents请求
type DeleteAgentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentIds      []string               `protobuf:"bytes,1,rep,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"` // Agent唯一标识列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentsReq) Reset() {
	*x = DeleteAgentsReq{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentsReq) ProtoMessage() {}

func (x *DeleteAgentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentsReq.ProtoReflect.Descriptor instead.
func (*DeleteAgentsReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAgentsReq) GetAgentIds() []string {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

// DeleteAgentsRsp 删除Agents响应
type DeleteAgentsRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentsRsp) Reset() {
	*x = DeleteAgentsRsp{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentsRsp) ProtoMessage() {}

func (x *DeleteAgentsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentsRsp.ProtoReflect.Descriptor instead.
func (*DeleteAgentsRsp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x10go_sapaude_dogai\"\xda\x03\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x03 \x01(\tR\tagentName\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x04 \x01(\tR\tagentType\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12*\n" +
	"\x11using_provider_id\x18\x06 \x01(\tR\x0fusingProviderId\x12\x1f\n" +
	"\vusing_model\x18\a \x01(\tR\n" +
	"usingModel\x12\x1d\n" +
	"\n" +
	"sys_prompt\x18\b \x01(\tR\tsysPrompt\x12\x1b\n" +
	"\tai_prompt\x18\t \x01(\tR\baiPrompt\x12\x14\n" +
	"\x05model\x18\n" +
	" \x01(\tR\x05model\x12 \n" +
	"\vtemperature\x18\v \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\f \x01(\x05R\tmaxTokens\x12\x13\n" +
	"\x05top_p\x18\r \x01(\x01R\x04topP\x12\x13\n" +
	"\x05top_k\x18\x0e \x01(\x05R\x04topK\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\tR\tupdatedAt\"&\n" +
	"\tCondAgent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"=\n" +
	"\fSaveAgentReq\x12-\n" +
	"\x05agent\x18\x01 \x01(\v2\x17.go_sapaude_dogai.AgentR\x05agent\"\x0e\n" +
	"\fSaveAgentRsp\"Z\n" +
	"\x0eUpdateAgentReq\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12-\n" +
	"\x05agent\x18\x02 \x01(\v2\x17.go_sapaude_dogai.AgentR\x05agent\"\x10\n" +
	"\x0eUpdateAgentRsp\"M\n" +
	"\x10GetAgentListsReq\x129\n" +
	"\tcondition\x18\x01 \x01(\v2\x1b.go_sapaude_dogai.CondAgentR\tcondition\"C\n" +
	"\x10GetAgentListsRsp\x12/\n" +
	"\x06agents\x18\x01 \x03(\v2\x17.go_sapaude_dogai.AgentR\x06agents\"(\n" +
	"\vGetAgentReq\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"<\n" +
	"\vGetAgentRsp\x12-\n" +
	"\x05agent\x18\x01 \x01(\v2\x17.go_sapaude_dogai.AgentR\x05agent\".\n" +
	"\x0fDeleteAgentsReq\x12\x1b\n" +
	"\tagent_ids\x18\x01 \x03(\tR\bagentIds\"\x11\n" +
	"\x0fDeleteAgentsRsp*=\n" +
	"\tAgentType\x12\x1a\n" +
	"\x16AGENT_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10AGENT_TYPE_REACT\x10\x01B1Z/github.com/sapaude/protocol/ai/go_sapaude_dogaib\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_agent_proto_goTypes = []any{
	(AgentType)(0),           // 0: go_sapaude_dogai.AgentType
	(*Agent)(nil),            // 1: go_sapaude_dogai.Agent
	(*CondAgent)(nil),        // 2: go_sapaude_dogai.CondAgent
	(*SaveAgentReq)(nil),     // 3: go_sapaude_dogai.SaveAgentReq
	(*SaveAgentRsp)(nil),     // 4: go_sapaude_dogai.SaveAgentRsp
	(*UpdateAgentReq)(nil),   // 5: go_sapaude_dogai.UpdateAgentReq
	(*UpdateAgentRsp)(nil),   // 6: go_sapaude_dogai.UpdateAgentRsp
	(*GetAgentListsReq)(nil), // 7: go_sapaude_dogai.GetAgentListsReq
	(*GetAgentListsRsp)(nil), // 8: go_sapaude_dogai.GetAgentListsRsp
	(*GetAgentReq)(nil),      // 9: go_sapaude_dogai.GetAgentReq
	(*GetAgentRsp)(nil),      // 10: go_sapaude_dogai.GetAgentRsp
	(*DeleteAgentsReq)(nil),  // 11: go_sapaude_dogai.DeleteAgentsReq
	(*DeleteAgentsRsp)(nil),  // 12: go_sapaude_dogai.DeleteAgentsRsp
}
var file_agent_proto_depIdxs = []int32{
	1, // 0: go_sapaude_dogai.SaveAgentReq.agent:type_name -> go_sapaude_dogai.Agent
	1, // 1: go_sapaude_dogai.UpdateAgentReq.agent:type_name -> go_sapaude_dogai.Agent
	2, // 2: go_sapaude_dogai.GetAgentListsReq.condition:type_name -> go_sapaude_dogai.CondAgent
	1, // 3: go_sapaude_dogai.GetAgentListsRsp.agents:type_name -> go_sapaude_dogai.Agent
	1, // 4: go_sapaude_dogai.GetAgentRsp.agent:type_name -> go_sapaude_dogai.Agent
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
