// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: dog_ai.proto

package go_sapaude_dogai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Call AI 流式请求
type CallAIStreamReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // 用户选中的agent_id
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`              // 用户问题
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallAIStreamReq) Reset() {
	*x = CallAIStreamReq{}
	mi := &file_dog_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallAIStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallAIStreamReq) ProtoMessage() {}

func (x *CallAIStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_dog_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallAIStreamReq.ProtoReflect.Descriptor instead.
func (*CallAIStreamReq) Descriptor() ([]byte, []int) {
	return file_dog_ai_proto_rawDescGZIP(), []int{0}
}

func (x *CallAIStreamReq) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CallAIStreamReq) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type CallAIStreamRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallAIStreamRsp) Reset() {
	*x = CallAIStreamRsp{}
	mi := &file_dog_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallAIStreamRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallAIStreamRsp) ProtoMessage() {}

func (x *CallAIStreamRsp) ProtoReflect() protoreflect.Message {
	mi := &file_dog_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallAIStreamRsp.ProtoReflect.Descriptor instead.
func (*CallAIStreamRsp) Descriptor() ([]byte, []int) {
	return file_dog_ai_proto_rawDescGZIP(), []int{1}
}

var File_dog_ai_proto protoreflect.FileDescriptor

const file_dog_ai_proto_rawDesc = "" +
	"\n" +
	"\fdog_ai.proto\x12\x10go_sapaude_dogai\"H\n" +
	"\x0fCallAIStreamReq\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\"\x11\n" +
	"\x0fCallAIStreamRspB1Z/github.com/sapaude/protocol/ai/go_sapaude_dogaib\x06proto3"

var (
	file_dog_ai_proto_rawDescOnce sync.Once
	file_dog_ai_proto_rawDescData []byte
)

func file_dog_ai_proto_rawDescGZIP() []byte {
	file_dog_ai_proto_rawDescOnce.Do(func() {
		file_dog_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dog_ai_proto_rawDesc), len(file_dog_ai_proto_rawDesc)))
	})
	return file_dog_ai_proto_rawDescData
}

var file_dog_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dog_ai_proto_goTypes = []any{
	(*CallAIStreamReq)(nil), // 0: go_sapaude_dogai.CallAIStreamReq
	(*CallAIStreamRsp)(nil), // 1: go_sapaude_dogai.CallAIStreamRsp
}
var file_dog_ai_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dog_ai_proto_init() }
func file_dog_ai_proto_init() {
	if File_dog_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dog_ai_proto_rawDesc), len(file_dog_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dog_ai_proto_goTypes,
		DependencyIndexes: file_dog_ai_proto_depIdxs,
		MessageInfos:      file_dog_ai_proto_msgTypes,
	}.Build()
	File_dog_ai_proto = out.File
	file_dog_ai_proto_goTypes = nil
	file_dog_ai_proto_depIdxs = nil
}
