// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: go_sapaude_dogai.proto

package go_sapaude_dogai

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_go_sapaude_dogai_proto protoreflect.FileDescriptor

const file_go_sapaude_dogai_proto_rawDesc = "" +
	"\n" +
	"\x16go_sapaude_dogai.proto\x12\x10go_sapaude_dogai\x1a\x1cgoogle/api/annotations.proto\x1a\x0esettings.proto\x1a\x0eprovider.proto\x1a\vagent.proto\x1a\fdog_ai.proto2\xb6\r\n" +
	"\x0eGoSapaudeDogAI\x12\x83\x01\n" +
	"\x12GetGeneralSettings\x12'.go_sapaude_dogai.GetGeneralSettingsReq\x1a'.go_sapaude_dogai.GetGeneralSettingsRsp\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/GetGeneralSettings\x12\x8a\x01\n" +
	"\x13SaveGeneralSettings\x12(.go_sapaude_dogai.SaveGeneralSettingsReq\x1a(.go_sapaude_dogai.SaveGeneralSettingsRsp\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/SaveGeneralSettings\x12n\n" +
	"\fSaveProvider\x12!.go_sapaude_dogai.SaveProviderReq\x1a!.go_sapaude_dogai.SaveProviderRsp\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/SaveProvider\x12v\n" +
	"\x0eUpdateProvider\x12#.go_sapaude_dogai.UpdateProviderReq\x1a#.go_sapaude_dogai.UpdateProviderRsp\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/UpdateProvider\x12~\n" +
	"\x10GetProviderLists\x12%.go_sapaude_dogai.GetProviderListsReq\x1a%.go_sapaude_dogai.GetProviderListsRsp\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/GetProviderLists\x12u\n" +
	"\vGetProvider\x12 .go_sapaude_dogai.GetProviderReq\x1a .go_sapaude_dogai.GetProviderRsp\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/GetProvider/{provider_id}\x12z\n" +
	"\x0fDeleteProviders\x12$.go_sapaude_dogai.DeleteProvidersReq\x1a$.go_sapaude_dogai.DeleteProvidersRsp\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/DeleteProviders\x12\xa9\x01\n" +
	"\x18GetProviderSupportModels\x12-.go_sapaude_dogai.GetProviderSupportModelsReq\x1a-.go_sapaude_dogai.GetProviderSupportModelsRsp\"/\x82\xd3\xe4\x93\x02)\x12'/GetProviderSupportModels/{provider_id}\x12b\n" +
	"\tSaveAgent\x12\x1e.go_sapaude_dogai.SaveAgentReq\x1a\x1e.go_sapaude_dogai.SaveAgentRsp\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/SaveAgent\x12j\n" +
	"\vUpdateAgent\x12 .go_sapaude_dogai.UpdateAgentReq\x1a .go_sapaude_dogai.UpdateAgentRsp\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/UpdateAgent\x12r\n" +
	"\rGetAgentLists\x12\".go_sapaude_dogai.GetAgentListsReq\x1a\".go_sapaude_dogai.GetAgentListsRsp\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/GetAgentLists\x12f\n" +
	"\bGetAgent\x12\x1d.go_sapaude_dogai.GetAgentReq\x1a\x1d.go_sapaude_dogai.GetAgentRsp\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/GetAgent/{agent_id}\x12n\n" +
	"\fDeleteAgents\x12!.go_sapaude_dogai.DeleteAgentsReq\x1a!.go_sapaude_dogai.DeleteAgentsRsp\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/DeleteAgents\x12n\n" +
	"\fCallAIStream\x12!.go_sapaude_dogai.CallAIStreamReq\x1a!.go_sapaude_dogai.CallAIStreamRsp\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/CallAIStreamB1Z/github.com/sapaude/protocol/ai/go_sapaude_dogaib\x06proto3"

var file_go_sapaude_dogai_proto_goTypes = []any{
	(*GetGeneralSettingsReq)(nil),       // 0: go_sapaude_dogai.GetGeneralSettingsReq
	(*SaveGeneralSettingsReq)(nil),      // 1: go_sapaude_dogai.SaveGeneralSettingsReq
	(*SaveProviderReq)(nil),             // 2: go_sapaude_dogai.SaveProviderReq
	(*UpdateProviderReq)(nil),           // 3: go_sapaude_dogai.UpdateProviderReq
	(*GetProviderListsReq)(nil),         // 4: go_sapaude_dogai.GetProviderListsReq
	(*GetProviderReq)(nil),              // 5: go_sapaude_dogai.GetProviderReq
	(*DeleteProvidersReq)(nil),          // 6: go_sapaude_dogai.DeleteProvidersReq
	(*GetProviderSupportModelsReq)(nil), // 7: go_sapaude_dogai.GetProviderSupportModelsReq
	(*SaveAgentReq)(nil),                // 8: go_sapaude_dogai.SaveAgentReq
	(*UpdateAgentReq)(nil),              // 9: go_sapaude_dogai.UpdateAgentReq
	(*GetAgentListsReq)(nil),            // 10: go_sapaude_dogai.GetAgentListsReq
	(*GetAgentReq)(nil),                 // 11: go_sapaude_dogai.GetAgentReq
	(*DeleteAgentsReq)(nil),             // 12: go_sapaude_dogai.DeleteAgentsReq
	(*CallAIStreamReq)(nil),             // 13: go_sapaude_dogai.CallAIStreamReq
	(*GetGeneralSettingsRsp)(nil),       // 14: go_sapaude_dogai.GetGeneralSettingsRsp
	(*SaveGeneralSettingsRsp)(nil),      // 15: go_sapaude_dogai.SaveGeneralSettingsRsp
	(*SaveProviderRsp)(nil),             // 16: go_sapaude_dogai.SaveProviderRsp
	(*UpdateProviderRsp)(nil),           // 17: go_sapaude_dogai.UpdateProviderRsp
	(*GetProviderListsRsp)(nil),         // 18: go_sapaude_dogai.GetProviderListsRsp
	(*GetProviderRsp)(nil),              // 19: go_sapaude_dogai.GetProviderRsp
	(*DeleteProvidersRsp)(nil),          // 20: go_sapaude_dogai.DeleteProvidersRsp
	(*GetProviderSupportModelsRsp)(nil), // 21: go_sapaude_dogai.GetProviderSupportModelsRsp
	(*SaveAgentRsp)(nil),                // 22: go_sapaude_dogai.SaveAgentRsp
	(*UpdateAgentRsp)(nil),              // 23: go_sapaude_dogai.UpdateAgentRsp
	(*GetAgentListsRsp)(nil),            // 24: go_sapaude_dogai.GetAgentListsRsp
	(*GetAgentRsp)(nil),                 // 25: go_sapaude_dogai.GetAgentRsp
	(*DeleteAgentsRsp)(nil),             // 26: go_sapaude_dogai.DeleteAgentsRsp
	(*CallAIStreamRsp)(nil),             // 27: go_sapaude_dogai.CallAIStreamRsp
}
var file_go_sapaude_dogai_proto_depIdxs = []int32{
	0,  // 0: go_sapaude_dogai.GoSapaudeDogAI.GetGeneralSettings:input_type -> go_sapaude_dogai.GetGeneralSettingsReq
	1,  // 1: go_sapaude_dogai.GoSapaudeDogAI.SaveGeneralSettings:input_type -> go_sapaude_dogai.SaveGeneralSettingsReq
	2,  // 2: go_sapaude_dogai.GoSapaudeDogAI.SaveProvider:input_type -> go_sapaude_dogai.SaveProviderReq
	3,  // 3: go_sapaude_dogai.GoSapaudeDogAI.UpdateProvider:input_type -> go_sapaude_dogai.UpdateProviderReq
	4,  // 4: go_sapaude_dogai.GoSapaudeDogAI.GetProviderLists:input_type -> go_sapaude_dogai.GetProviderListsReq
	5,  // 5: go_sapaude_dogai.GoSapaudeDogAI.GetProvider:input_type -> go_sapaude_dogai.GetProviderReq
	6,  // 6: go_sapaude_dogai.GoSapaudeDogAI.DeleteProviders:input_type -> go_sapaude_dogai.DeleteProvidersReq
	7,  // 7: go_sapaude_dogai.GoSapaudeDogAI.GetProviderSupportModels:input_type -> go_sapaude_dogai.GetProviderSupportModelsReq
	8,  // 8: go_sapaude_dogai.GoSapaudeDogAI.SaveAgent:input_type -> go_sapaude_dogai.SaveAgentReq
	9,  // 9: go_sapaude_dogai.GoSapaudeDogAI.UpdateAgent:input_type -> go_sapaude_dogai.UpdateAgentReq
	10, // 10: go_sapaude_dogai.GoSapaudeDogAI.GetAgentLists:input_type -> go_sapaude_dogai.GetAgentListsReq
	11, // 11: go_sapaude_dogai.GoSapaudeDogAI.GetAgent:input_type -> go_sapaude_dogai.GetAgentReq
	12, // 12: go_sapaude_dogai.GoSapaudeDogAI.DeleteAgents:input_type -> go_sapaude_dogai.DeleteAgentsReq
	13, // 13: go_sapaude_dogai.GoSapaudeDogAI.CallAIStream:input_type -> go_sapaude_dogai.CallAIStreamReq
	14, // 14: go_sapaude_dogai.GoSapaudeDogAI.GetGeneralSettings:output_type -> go_sapaude_dogai.GetGeneralSettingsRsp
	15, // 15: go_sapaude_dogai.GoSapaudeDogAI.SaveGeneralSettings:output_type -> go_sapaude_dogai.SaveGeneralSettingsRsp
	16, // 16: go_sapaude_dogai.GoSapaudeDogAI.SaveProvider:output_type -> go_sapaude_dogai.SaveProviderRsp
	17, // 17: go_sapaude_dogai.GoSapaudeDogAI.UpdateProvider:output_type -> go_sapaude_dogai.UpdateProviderRsp
	18, // 18: go_sapaude_dogai.GoSapaudeDogAI.GetProviderLists:output_type -> go_sapaude_dogai.GetProviderListsRsp
	19, // 19: go_sapaude_dogai.GoSapaudeDogAI.GetProvider:output_type -> go_sapaude_dogai.GetProviderRsp
	20, // 20: go_sapaude_dogai.GoSapaudeDogAI.DeleteProviders:output_type -> go_sapaude_dogai.DeleteProvidersRsp
	21, // 21: go_sapaude_dogai.GoSapaudeDogAI.GetProviderSupportModels:output_type -> go_sapaude_dogai.GetProviderSupportModelsRsp
	22, // 22: go_sapaude_dogai.GoSapaudeDogAI.SaveAgent:output_type -> go_sapaude_dogai.SaveAgentRsp
	23, // 23: go_sapaude_dogai.GoSapaudeDogAI.UpdateAgent:output_type -> go_sapaude_dogai.UpdateAgentRsp
	24, // 24: go_sapaude_dogai.GoSapaudeDogAI.GetAgentLists:output_type -> go_sapaude_dogai.GetAgentListsRsp
	25, // 25: go_sapaude_dogai.GoSapaudeDogAI.GetAgent:output_type -> go_sapaude_dogai.GetAgentRsp
	26, // 26: go_sapaude_dogai.GoSapaudeDogAI.DeleteAgents:output_type -> go_sapaude_dogai.DeleteAgentsRsp
	27, // 27: go_sapaude_dogai.GoSapaudeDogAI.CallAIStream:output_type -> go_sapaude_dogai.CallAIStreamRsp
	14, // [14:28] is the sub-list for method output_type
	0,  // [0:14] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_go_sapaude_dogai_proto_init() }
func file_go_sapaude_dogai_proto_init() {
	if File_go_sapaude_dogai_proto != nil {
		return
	}
	file_settings_proto_init()
	file_provider_proto_init()
	file_agent_proto_init()
	file_dog_ai_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_sapaude_dogai_proto_rawDesc), len(file_go_sapaude_dogai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_sapaude_dogai_proto_goTypes,
		DependencyIndexes: file_go_sapaude_dogai_proto_depIdxs,
	}.Build()
	File_go_sapaude_dogai_proto = out.File
	file_go_sapaude_dogai_proto_goTypes = nil
	file_go_sapaude_dogai_proto_depIdxs = nil
}
