// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: go_sapaude_dogai.proto

package go_sapaude_dogai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoSapaudeDogAI_GetAvailableModels_FullMethodName = "/go_sapaude_dogai.GoSapaudeDogAI/GetAvailableModels"
)

// GoSapaudeDogAIClient is the client API for GoSapaudeDogAI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Sapaude DOGAI服务
type GoSapaudeDogAIClient interface {
	// 查询可用的模型
	GetAvailableModels(ctx context.Context, in *GetAvailableModelsReq, opts ...grpc.CallOption) (*GetAvailableModelsRsp, error)
}

type goSapaudeDogAIClient struct {
	cc grpc.ClientConnInterface
}

func NewGoSapaudeDogAIClient(cc grpc.ClientConnInterface) GoSapaudeDogAIClient {
	return &goSapaudeDogAIClient{cc}
}

func (c *goSapaudeDogAIClient) GetAvailableModels(ctx context.Context, in *GetAvailableModelsReq, opts ...grpc.CallOption) (*GetAvailableModelsRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableModelsRsp)
	err := c.cc.Invoke(ctx, GoSapaudeDogAI_GetAvailableModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoSapaudeDogAIServer is the server API for GoSapaudeDogAI service.
// All implementations must embed UnimplementedGoSapaudeDogAIServer
// for forward compatibility.
//
// Sapaude DOGAI服务
type GoSapaudeDogAIServer interface {
	// 查询可用的模型
	GetAvailableModels(context.Context, *GetAvailableModelsReq) (*GetAvailableModelsRsp, error)
	mustEmbedUnimplementedGoSapaudeDogAIServer()
}

// UnimplementedGoSapaudeDogAIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoSapaudeDogAIServer struct{}

func (UnimplementedGoSapaudeDogAIServer) GetAvailableModels(context.Context, *GetAvailableModelsReq) (*GetAvailableModelsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableModels not implemented")
}
func (UnimplementedGoSapaudeDogAIServer) mustEmbedUnimplementedGoSapaudeDogAIServer() {}
func (UnimplementedGoSapaudeDogAIServer) testEmbeddedByValue()                        {}

// UnsafeGoSapaudeDogAIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoSapaudeDogAIServer will
// result in compilation errors.
type UnsafeGoSapaudeDogAIServer interface {
	mustEmbedUnimplementedGoSapaudeDogAIServer()
}

func RegisterGoSapaudeDogAIServer(s grpc.ServiceRegistrar, srv GoSapaudeDogAIServer) {
	// If the following call pancis, it indicates UnimplementedGoSapaudeDogAIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoSapaudeDogAI_ServiceDesc, srv)
}

func _GoSapaudeDogAI_GetAvailableModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableModelsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSapaudeDogAIServer).GetAvailableModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoSapaudeDogAI_GetAvailableModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSapaudeDogAIServer).GetAvailableModels(ctx, req.(*GetAvailableModelsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GoSapaudeDogAI_ServiceDesc is the grpc.ServiceDesc for GoSapaudeDogAI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoSapaudeDogAI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go_sapaude_dogai.GoSapaudeDogAI",
	HandlerType: (*GoSapaudeDogAIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAvailableModels",
			Handler:    _GoSapaudeDogAI_GetAvailableModels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go_sapaude_dogai.proto",
}
