// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: go_sapaude_dogai.proto

package go_sapaude_dogai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoSapaudeDogAI_GetGeneralSettings_FullMethodName       = "/go_sapaude_dogai.GoSapaudeDogAI/GetGeneralSettings"
	GoSapaudeDogAI_SaveGeneralSettings_FullMethodName      = "/go_sapaude_dogai.GoSapaudeDogAI/SaveGeneralSettings"
	GoSapaudeDogAI_SaveProvider_FullMethodName             = "/go_sapaude_dogai.GoSapaudeDogAI/SaveProvider"
	GoSapaudeDogAI_UpdateProvider_FullMethodName           = "/go_sapaude_dogai.GoSapaudeDogAI/UpdateProvider"
	GoSapaudeDogAI_GetProviderLists_FullMethodName         = "/go_sapaude_dogai.GoSapaudeDogAI/GetProviderLists"
	GoSapaudeDogAI_GetProvider_FullMethodName              = "/go_sapaude_dogai.GoSapaudeDogAI/GetProvider"
	GoSapaudeDogAI_DeleteProviders_FullMethodName          = "/go_sapaude_dogai.GoSapaudeDogAI/DeleteProviders"
	GoSapaudeDogAI_GetProviderSupportModels_FullMethodName = "/go_sapaude_dogai.GoSapaudeDogAI/GetProviderSupportModels"
	GoSapaudeDogAI_SaveAgent_FullMethodName                = "/go_sapaude_dogai.GoSapaudeDogAI/SaveAgent"
	GoSapaudeDogAI_UpdateAgent_FullMethodName              = "/go_sapaude_dogai.GoSapaudeDogAI/UpdateAgent"
	GoSapaudeDogAI_GetAgentLists_FullMethodName            = "/go_sapaude_dogai.GoSapaudeDogAI/GetAgentLists"
	GoSapaudeDogAI_GetAgent_FullMethodName                 = "/go_sapaude_dogai.GoSapaudeDogAI/GetAgent"
	GoSapaudeDogAI_DeleteAgents_FullMethodName             = "/go_sapaude_dogai.GoSapaudeDogAI/DeleteAgents"
	GoSapaudeDogAI_GetAvailableModels_FullMethodName       = "/go_sapaude_dogai.GoSapaudeDogAI/GetAvailableModels"
	GoSapaudeDogAI_CallAIStream_FullMethodName             = "/go_sapaude_dogai.GoSapaudeDogAI/CallAIStream"
)

// GoSapaudeDogAIClient is the client API for GoSapaudeDogAI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Sapaude DOGAI服务
type GoSapaudeDogAIClient interface {
	// ---- Setting配置  ----
	GetGeneralSettings(ctx context.Context, in *GetGeneralSettingsReq, opts ...grpc.CallOption) (*GetGeneralSettingsRsp, error)
	// 保存通用配置(兼容旧接口)
	SaveGeneralSettings(ctx context.Context, in *SaveGeneralSettingsReq, opts ...grpc.CallOption) (*SaveGeneralSettingsRsp, error)
	// 保存Provider配置
	SaveProvider(ctx context.Context, in *SaveProviderReq, opts ...grpc.CallOption) (*SaveProviderRsp, error)
	// 更新Provider配置
	UpdateProvider(ctx context.Context, in *UpdateProviderReq, opts ...grpc.CallOption) (*UpdateProviderRsp, error)
	// 查询Provider列表
	GetProviderLists(ctx context.Context, in *GetProviderListsReq, opts ...grpc.CallOption) (*GetProviderListsRsp, error)
	// 获取指定Provider配置
	GetProvider(ctx context.Context, in *GetProviderReq, opts ...grpc.CallOption) (*GetProviderRsp, error)
	// 删除指定的Providers
	DeleteProviders(ctx context.Context, in *DeleteProvidersReq, opts ...grpc.CallOption) (*DeleteProvidersRsp, error)
	// 获取Provider支持的模型列表
	GetProviderSupportModels(ctx context.Context, in *GetProviderSupportModelsReq, opts ...grpc.CallOption) (*GetProviderSupportModelsRsp, error)
	// 保存Agent配置
	SaveAgent(ctx context.Context, in *SaveAgentReq, opts ...grpc.CallOption) (*SaveAgentRsp, error)
	// 更新Agent配置
	UpdateAgent(ctx context.Context, in *UpdateAgentReq, opts ...grpc.CallOption) (*UpdateAgentRsp, error)
	// 查询Agent列表
	GetAgentLists(ctx context.Context, in *GetAgentListsReq, opts ...grpc.CallOption) (*GetAgentListsRsp, error)
	// 获取指定Agent配置
	GetAgent(ctx context.Context, in *GetAgentReq, opts ...grpc.CallOption) (*GetAgentRsp, error)
	// 删除指定的Agents
	DeleteAgents(ctx context.Context, in *DeleteAgentsReq, opts ...grpc.CallOption) (*DeleteAgentsRsp, error)
	// 查询可用的模型
	GetAvailableModels(ctx context.Context, in *GetAvailableModelsReq, opts ...grpc.CallOption) (*GetAvailableModelsRsp, error)
	// AI对话
	CallAIStream(ctx context.Context, in *CallAIStreamReq, opts ...grpc.CallOption) (*CallAIStreamRsp, error)
}

type goSapaudeDogAIClient struct {
	cc grpc.ClientConnInterface
}

func NewGoSapaudeDogAIClient(cc grpc.ClientConnInterface) GoSapaudeDogAIClient {
	return &goSapaudeDogAIClient{cc}
}

func (c *goSapaudeDogAIClient) GetGeneralSettings(ctx context.Context, in *GetGeneralSettingsReq, opts ...grpc.CallOption) (*GetGeneralSettingsRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGeneralSettingsRsp)
	err := c.cc.Invoke(ctx, GoSapaudeDogAI_GetGeneralSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goSapaudeDogAIClient) SaveGeneralSettings(ctx context.Context, in *SaveGeneralSettingsReq, opts ...grpc.CallOption) (*SaveGeneralSettingsRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveGeneralSettingsRsp)
	err := c.cc.Invoke(ctx, GoSapaudeDogAI_SaveGeneralSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goSapaudeDogAIClient) SaveProvider(ctx context.Context, in *SaveProviderReq, opts ...grpc.CallOption) (*SaveProviderRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveProviderRsp)
	err := c.cc.Invoke(ctx, GoSapaudeDogAI_SaveProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goSapaudeDogAIClient) UpdateProvider(ctx context.Context, in *UpdateProviderReq, opts ...grpc.CallOption) (*UpdateProviderRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProviderRsp)
	err := c.cc.Invoke(ctx, GoSapaudeDogAI_UpdateProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goSapaudeDogAIClient) GetProviderLists(ctx context.Context, in *GetProviderListsReq, opts ...grpc.CallOption) (*GetProviderListsRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderListsRsp)
	err := c.cc.Invoke(ctx, GoSapaudeDogAI_GetProviderLists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goSapaudeDogAIClient) GetProvider(ctx context.Context, in *GetProviderReq, opts ...grpc.CallOption) (*GetProviderRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderRsp)
	err := c.cc.Invoke(ctx, GoSapaudeDogAI_GetProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goSapaudeDogAIClient) DeleteProviders(ctx context.Context, in *DeleteProvidersReq, opts ...grpc.CallOption) (*DeleteProvidersRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProvidersRsp)
	err := c.cc.Invoke(ctx, GoSapaudeDogAI_DeleteProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goSapaudeDogAIClient) GetProviderSupportModels(ctx context.Context, in *GetProviderSupportModelsReq, opts ...grpc.CallOption) (*GetProviderSupportModelsRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderSupportModelsRsp)
	err := c.cc.Invoke(ctx, GoSapaudeDogAI_GetProviderSupportModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goSapaudeDogAIClient) SaveAgent(ctx context.Context, in *SaveAgentReq, opts ...grpc.CallOption) (*SaveAgentRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveAgentRsp)
	err := c.cc.Invoke(ctx, GoSapaudeDogAI_SaveAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goSapaudeDogAIClient) UpdateAgent(ctx context.Context, in *UpdateAgentReq, opts ...grpc.CallOption) (*UpdateAgentRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAgentRsp)
	err := c.cc.Invoke(ctx, GoSapaudeDogAI_UpdateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goSapaudeDogAIClient) GetAgentLists(ctx context.Context, in *GetAgentListsReq, opts ...grpc.CallOption) (*GetAgentListsRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentListsRsp)
	err := c.cc.Invoke(ctx, GoSapaudeDogAI_GetAgentLists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goSapaudeDogAIClient) GetAgent(ctx context.Context, in *GetAgentReq, opts ...grpc.CallOption) (*GetAgentRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentRsp)
	err := c.cc.Invoke(ctx, GoSapaudeDogAI_GetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goSapaudeDogAIClient) DeleteAgents(ctx context.Context, in *DeleteAgentsReq, opts ...grpc.CallOption) (*DeleteAgentsRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAgentsRsp)
	err := c.cc.Invoke(ctx, GoSapaudeDogAI_DeleteAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goSapaudeDogAIClient) GetAvailableModels(ctx context.Context, in *GetAvailableModelsReq, opts ...grpc.CallOption) (*GetAvailableModelsRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableModelsRsp)
	err := c.cc.Invoke(ctx, GoSapaudeDogAI_GetAvailableModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goSapaudeDogAIClient) CallAIStream(ctx context.Context, in *CallAIStreamReq, opts ...grpc.CallOption) (*CallAIStreamRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallAIStreamRsp)
	err := c.cc.Invoke(ctx, GoSapaudeDogAI_CallAIStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoSapaudeDogAIServer is the server API for GoSapaudeDogAI service.
// All implementations must embed UnimplementedGoSapaudeDogAIServer
// for forward compatibility.
//
// Sapaude DOGAI服务
type GoSapaudeDogAIServer interface {
	// ---- Setting配置  ----
	GetGeneralSettings(context.Context, *GetGeneralSettingsReq) (*GetGeneralSettingsRsp, error)
	// 保存通用配置(兼容旧接口)
	SaveGeneralSettings(context.Context, *SaveGeneralSettingsReq) (*SaveGeneralSettingsRsp, error)
	// 保存Provider配置
	SaveProvider(context.Context, *SaveProviderReq) (*SaveProviderRsp, error)
	// 更新Provider配置
	UpdateProvider(context.Context, *UpdateProviderReq) (*UpdateProviderRsp, error)
	// 查询Provider列表
	GetProviderLists(context.Context, *GetProviderListsReq) (*GetProviderListsRsp, error)
	// 获取指定Provider配置
	GetProvider(context.Context, *GetProviderReq) (*GetProviderRsp, error)
	// 删除指定的Providers
	DeleteProviders(context.Context, *DeleteProvidersReq) (*DeleteProvidersRsp, error)
	// 获取Provider支持的模型列表
	GetProviderSupportModels(context.Context, *GetProviderSupportModelsReq) (*GetProviderSupportModelsRsp, error)
	// 保存Agent配置
	SaveAgent(context.Context, *SaveAgentReq) (*SaveAgentRsp, error)
	// 更新Agent配置
	UpdateAgent(context.Context, *UpdateAgentReq) (*UpdateAgentRsp, error)
	// 查询Agent列表
	GetAgentLists(context.Context, *GetAgentListsReq) (*GetAgentListsRsp, error)
	// 获取指定Agent配置
	GetAgent(context.Context, *GetAgentReq) (*GetAgentRsp, error)
	// 删除指定的Agents
	DeleteAgents(context.Context, *DeleteAgentsReq) (*DeleteAgentsRsp, error)
	// 查询可用的模型
	GetAvailableModels(context.Context, *GetAvailableModelsReq) (*GetAvailableModelsRsp, error)
	// AI对话
	CallAIStream(context.Context, *CallAIStreamReq) (*CallAIStreamRsp, error)
	mustEmbedUnimplementedGoSapaudeDogAIServer()
}

// UnimplementedGoSapaudeDogAIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoSapaudeDogAIServer struct{}

func (UnimplementedGoSapaudeDogAIServer) GetGeneralSettings(context.Context, *GetGeneralSettingsReq) (*GetGeneralSettingsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGeneralSettings not implemented")
}
func (UnimplementedGoSapaudeDogAIServer) SaveGeneralSettings(context.Context, *SaveGeneralSettingsReq) (*SaveGeneralSettingsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveGeneralSettings not implemented")
}
func (UnimplementedGoSapaudeDogAIServer) SaveProvider(context.Context, *SaveProviderReq) (*SaveProviderRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveProvider not implemented")
}
func (UnimplementedGoSapaudeDogAIServer) UpdateProvider(context.Context, *UpdateProviderReq) (*UpdateProviderRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProvider not implemented")
}
func (UnimplementedGoSapaudeDogAIServer) GetProviderLists(context.Context, *GetProviderListsReq) (*GetProviderListsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviderLists not implemented")
}
func (UnimplementedGoSapaudeDogAIServer) GetProvider(context.Context, *GetProviderReq) (*GetProviderRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProvider not implemented")
}
func (UnimplementedGoSapaudeDogAIServer) DeleteProviders(context.Context, *DeleteProvidersReq) (*DeleteProvidersRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProviders not implemented")
}
func (UnimplementedGoSapaudeDogAIServer) GetProviderSupportModels(context.Context, *GetProviderSupportModelsReq) (*GetProviderSupportModelsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviderSupportModels not implemented")
}
func (UnimplementedGoSapaudeDogAIServer) SaveAgent(context.Context, *SaveAgentReq) (*SaveAgentRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveAgent not implemented")
}
func (UnimplementedGoSapaudeDogAIServer) UpdateAgent(context.Context, *UpdateAgentReq) (*UpdateAgentRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgent not implemented")
}
func (UnimplementedGoSapaudeDogAIServer) GetAgentLists(context.Context, *GetAgentListsReq) (*GetAgentListsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentLists not implemented")
}
func (UnimplementedGoSapaudeDogAIServer) GetAgent(context.Context, *GetAgentReq) (*GetAgentRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedGoSapaudeDogAIServer) DeleteAgents(context.Context, *DeleteAgentsReq) (*DeleteAgentsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAgents not implemented")
}
func (UnimplementedGoSapaudeDogAIServer) GetAvailableModels(context.Context, *GetAvailableModelsReq) (*GetAvailableModelsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableModels not implemented")
}
func (UnimplementedGoSapaudeDogAIServer) CallAIStream(context.Context, *CallAIStreamReq) (*CallAIStreamRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallAIStream not implemented")
}
func (UnimplementedGoSapaudeDogAIServer) mustEmbedUnimplementedGoSapaudeDogAIServer() {}
func (UnimplementedGoSapaudeDogAIServer) testEmbeddedByValue()                        {}

// UnsafeGoSapaudeDogAIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoSapaudeDogAIServer will
// result in compilation errors.
type UnsafeGoSapaudeDogAIServer interface {
	mustEmbedUnimplementedGoSapaudeDogAIServer()
}

func RegisterGoSapaudeDogAIServer(s grpc.ServiceRegistrar, srv GoSapaudeDogAIServer) {
	// If the following call pancis, it indicates UnimplementedGoSapaudeDogAIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoSapaudeDogAI_ServiceDesc, srv)
}

func _GoSapaudeDogAI_GetGeneralSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGeneralSettingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSapaudeDogAIServer).GetGeneralSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoSapaudeDogAI_GetGeneralSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSapaudeDogAIServer).GetGeneralSettings(ctx, req.(*GetGeneralSettingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoSapaudeDogAI_SaveGeneralSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveGeneralSettingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSapaudeDogAIServer).SaveGeneralSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoSapaudeDogAI_SaveGeneralSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSapaudeDogAIServer).SaveGeneralSettings(ctx, req.(*SaveGeneralSettingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoSapaudeDogAI_SaveProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveProviderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSapaudeDogAIServer).SaveProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoSapaudeDogAI_SaveProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSapaudeDogAIServer).SaveProvider(ctx, req.(*SaveProviderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoSapaudeDogAI_UpdateProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProviderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSapaudeDogAIServer).UpdateProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoSapaudeDogAI_UpdateProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSapaudeDogAIServer).UpdateProvider(ctx, req.(*UpdateProviderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoSapaudeDogAI_GetProviderLists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderListsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSapaudeDogAIServer).GetProviderLists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoSapaudeDogAI_GetProviderLists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSapaudeDogAIServer).GetProviderLists(ctx, req.(*GetProviderListsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoSapaudeDogAI_GetProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSapaudeDogAIServer).GetProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoSapaudeDogAI_GetProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSapaudeDogAIServer).GetProvider(ctx, req.(*GetProviderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoSapaudeDogAI_DeleteProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProvidersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSapaudeDogAIServer).DeleteProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoSapaudeDogAI_DeleteProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSapaudeDogAIServer).DeleteProviders(ctx, req.(*DeleteProvidersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoSapaudeDogAI_GetProviderSupportModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderSupportModelsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSapaudeDogAIServer).GetProviderSupportModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoSapaudeDogAI_GetProviderSupportModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSapaudeDogAIServer).GetProviderSupportModels(ctx, req.(*GetProviderSupportModelsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoSapaudeDogAI_SaveAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveAgentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSapaudeDogAIServer).SaveAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoSapaudeDogAI_SaveAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSapaudeDogAIServer).SaveAgent(ctx, req.(*SaveAgentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoSapaudeDogAI_UpdateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSapaudeDogAIServer).UpdateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoSapaudeDogAI_UpdateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSapaudeDogAIServer).UpdateAgent(ctx, req.(*UpdateAgentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoSapaudeDogAI_GetAgentLists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentListsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSapaudeDogAIServer).GetAgentLists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoSapaudeDogAI_GetAgentLists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSapaudeDogAIServer).GetAgentLists(ctx, req.(*GetAgentListsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoSapaudeDogAI_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSapaudeDogAIServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoSapaudeDogAI_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSapaudeDogAIServer).GetAgent(ctx, req.(*GetAgentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoSapaudeDogAI_DeleteAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSapaudeDogAIServer).DeleteAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoSapaudeDogAI_DeleteAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSapaudeDogAIServer).DeleteAgents(ctx, req.(*DeleteAgentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoSapaudeDogAI_GetAvailableModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableModelsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSapaudeDogAIServer).GetAvailableModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoSapaudeDogAI_GetAvailableModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSapaudeDogAIServer).GetAvailableModels(ctx, req.(*GetAvailableModelsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoSapaudeDogAI_CallAIStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallAIStreamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSapaudeDogAIServer).CallAIStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoSapaudeDogAI_CallAIStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSapaudeDogAIServer).CallAIStream(ctx, req.(*CallAIStreamReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GoSapaudeDogAI_ServiceDesc is the grpc.ServiceDesc for GoSapaudeDogAI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoSapaudeDogAI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go_sapaude_dogai.GoSapaudeDogAI",
	HandlerType: (*GoSapaudeDogAIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGeneralSettings",
			Handler:    _GoSapaudeDogAI_GetGeneralSettings_Handler,
		},
		{
			MethodName: "SaveGeneralSettings",
			Handler:    _GoSapaudeDogAI_SaveGeneralSettings_Handler,
		},
		{
			MethodName: "SaveProvider",
			Handler:    _GoSapaudeDogAI_SaveProvider_Handler,
		},
		{
			MethodName: "UpdateProvider",
			Handler:    _GoSapaudeDogAI_UpdateProvider_Handler,
		},
		{
			MethodName: "GetProviderLists",
			Handler:    _GoSapaudeDogAI_GetProviderLists_Handler,
		},
		{
			MethodName: "GetProvider",
			Handler:    _GoSapaudeDogAI_GetProvider_Handler,
		},
		{
			MethodName: "DeleteProviders",
			Handler:    _GoSapaudeDogAI_DeleteProviders_Handler,
		},
		{
			MethodName: "GetProviderSupportModels",
			Handler:    _GoSapaudeDogAI_GetProviderSupportModels_Handler,
		},
		{
			MethodName: "SaveAgent",
			Handler:    _GoSapaudeDogAI_SaveAgent_Handler,
		},
		{
			MethodName: "UpdateAgent",
			Handler:    _GoSapaudeDogAI_UpdateAgent_Handler,
		},
		{
			MethodName: "GetAgentLists",
			Handler:    _GoSapaudeDogAI_GetAgentLists_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _GoSapaudeDogAI_GetAgent_Handler,
		},
		{
			MethodName: "DeleteAgents",
			Handler:    _GoSapaudeDogAI_DeleteAgents_Handler,
		},
		{
			MethodName: "GetAvailableModels",
			Handler:    _GoSapaudeDogAI_GetAvailableModels_Handler,
		},
		{
			MethodName: "CallAIStream",
			Handler:    _GoSapaudeDogAI_CallAIStream_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go_sapaude_dogai.proto",
}
