// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: go_sapaude_dogai.proto

package go_sapaude_dogai

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAvailableModelsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // Provider 唯一标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableModelsReq) Reset() {
	*x = GetAvailableModelsReq{}
	mi := &file_go_sapaude_dogai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableModelsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableModelsReq) ProtoMessage() {}

func (x *GetAvailableModelsReq) ProtoReflect() protoreflect.Message {
	mi := &file_go_sapaude_dogai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableModelsReq.ProtoReflect.Descriptor instead.
func (*GetAvailableModelsReq) Descriptor() ([]byte, []int) {
	return file_go_sapaude_dogai_proto_rawDescGZIP(), []int{0}
}

func (x *GetAvailableModelsReq) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type GetAvailableModelsRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []string               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"` // 可用的模型ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableModelsRsp) Reset() {
	*x = GetAvailableModelsRsp{}
	mi := &file_go_sapaude_dogai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableModelsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableModelsRsp) ProtoMessage() {}

func (x *GetAvailableModelsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_go_sapaude_dogai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableModelsRsp.ProtoReflect.Descriptor instead.
func (*GetAvailableModelsRsp) Descriptor() ([]byte, []int) {
	return file_go_sapaude_dogai_proto_rawDescGZIP(), []int{1}
}

func (x *GetAvailableModelsRsp) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

var File_go_sapaude_dogai_proto protoreflect.FileDescriptor

const file_go_sapaude_dogai_proto_rawDesc = "" +
	"\n" +
	"\x16go_sapaude_dogai.proto\x12\x10go_sapaude_dogai\x1a\x1cgoogle/api/annotations.proto\x1a\x0esettings.proto\x1a\x0eprovider.proto\x1a\vagent.proto\"8\n" +
	"\x15GetAvailableModelsReq\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"/\n" +
	"\x15GetAvailableModelsRsp\x12\x16\n" +
	"\x06models\x18\x01 \x03(\tR\x06models2\xb3\t\n" +
	"\x0eGoSapaudeDogAI\x12\x83\x01\n" +
	"\x12GetGeneralSettings\x12'.go_sapaude_dogai.GetGeneralSettingsReq\x1a'.go_sapaude_dogai.GetGeneralSettingsRsp\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/GetGeneralSettings\x12\x8a\x01\n" +
	"\x13SaveGeneralSettings\x12(.go_sapaude_dogai.SaveGeneralSettingsReq\x1a(.go_sapaude_dogai.SaveGeneralSettingsRsp\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/SaveGeneralSettings\x12n\n" +
	"\fSaveProvider\x12!.go_sapaude_dogai.SaveProviderReq\x1a!.go_sapaude_dogai.SaveProviderRsp\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/SaveProvider\x12v\n" +
	"\x0eUpdateProvider\x12#.go_sapaude_dogai.UpdateProviderReq\x1a#.go_sapaude_dogai.UpdateProviderRsp\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/UpdateProvider\x12~\n" +
	"\x10GetProviderLists\x12%.go_sapaude_dogai.GetProviderListsReq\x1a%.go_sapaude_dogai.GetProviderListsRsp\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/GetProviderLists\x12u\n" +
	"\vGetProvider\x12 .go_sapaude_dogai.GetProviderReq\x1a .go_sapaude_dogai.GetProviderRsp\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/GetProvider/{provider_id}\x12z\n" +
	"\x0fDeleteProviders\x12$.go_sapaude_dogai.DeleteProvidersReq\x1a$.go_sapaude_dogai.DeleteProvidersRsp\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/DeleteProviders\x12\xa9\x01\n" +
	"\x18GetProviderSupportModels\x12-.go_sapaude_dogai.GetProviderSupportModelsReq\x1a-.go_sapaude_dogai.GetProviderSupportModelsRsp\"/\x82\xd3\xe4\x93\x02)\x12'/GetProviderSupportModels/{provider_id}\x12\x86\x01\n" +
	"\x12GetAvailableModels\x12'.go_sapaude_dogai.GetAvailableModelsReq\x1a'.go_sapaude_dogai.GetAvailableModelsRsp\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/GetAvailableModelsB1Z/github.com/sapaude/protocol/ai/go_sapaude_dogaib\x06proto3"

var (
	file_go_sapaude_dogai_proto_rawDescOnce sync.Once
	file_go_sapaude_dogai_proto_rawDescData []byte
)

func file_go_sapaude_dogai_proto_rawDescGZIP() []byte {
	file_go_sapaude_dogai_proto_rawDescOnce.Do(func() {
		file_go_sapaude_dogai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_sapaude_dogai_proto_rawDesc), len(file_go_sapaude_dogai_proto_rawDesc)))
	})
	return file_go_sapaude_dogai_proto_rawDescData
}

var file_go_sapaude_dogai_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_go_sapaude_dogai_proto_goTypes = []any{
	(*GetAvailableModelsReq)(nil),       // 0: go_sapaude_dogai.GetAvailableModelsReq
	(*GetAvailableModelsRsp)(nil),       // 1: go_sapaude_dogai.GetAvailableModelsRsp
	(*GetGeneralSettingsReq)(nil),       // 2: go_sapaude_dogai.GetGeneralSettingsReq
	(*SaveGeneralSettingsReq)(nil),      // 3: go_sapaude_dogai.SaveGeneralSettingsReq
	(*SaveProviderReq)(nil),             // 4: go_sapaude_dogai.SaveProviderReq
	(*UpdateProviderReq)(nil),           // 5: go_sapaude_dogai.UpdateProviderReq
	(*GetProviderListsReq)(nil),         // 6: go_sapaude_dogai.GetProviderListsReq
	(*GetProviderReq)(nil),              // 7: go_sapaude_dogai.GetProviderReq
	(*DeleteProvidersReq)(nil),          // 8: go_sapaude_dogai.DeleteProvidersReq
	(*GetProviderSupportModelsReq)(nil), // 9: go_sapaude_dogai.GetProviderSupportModelsReq
	(*GetGeneralSettingsRsp)(nil),       // 10: go_sapaude_dogai.GetGeneralSettingsRsp
	(*SaveGeneralSettingsRsp)(nil),      // 11: go_sapaude_dogai.SaveGeneralSettingsRsp
	(*SaveProviderRsp)(nil),             // 12: go_sapaude_dogai.SaveProviderRsp
	(*UpdateProviderRsp)(nil),           // 13: go_sapaude_dogai.UpdateProviderRsp
	(*GetProviderListsRsp)(nil),         // 14: go_sapaude_dogai.GetProviderListsRsp
	(*GetProviderRsp)(nil),              // 15: go_sapaude_dogai.GetProviderRsp
	(*DeleteProvidersRsp)(nil),          // 16: go_sapaude_dogai.DeleteProvidersRsp
	(*GetProviderSupportModelsRsp)(nil), // 17: go_sapaude_dogai.GetProviderSupportModelsRsp
}
var file_go_sapaude_dogai_proto_depIdxs = []int32{
	2,  // 0: go_sapaude_dogai.GoSapaudeDogAI.GetGeneralSettings:input_type -> go_sapaude_dogai.GetGeneralSettingsReq
	3,  // 1: go_sapaude_dogai.GoSapaudeDogAI.SaveGeneralSettings:input_type -> go_sapaude_dogai.SaveGeneralSettingsReq
	4,  // 2: go_sapaude_dogai.GoSapaudeDogAI.SaveProvider:input_type -> go_sapaude_dogai.SaveProviderReq
	5,  // 3: go_sapaude_dogai.GoSapaudeDogAI.UpdateProvider:input_type -> go_sapaude_dogai.UpdateProviderReq
	6,  // 4: go_sapaude_dogai.GoSapaudeDogAI.GetProviderLists:input_type -> go_sapaude_dogai.GetProviderListsReq
	7,  // 5: go_sapaude_dogai.GoSapaudeDogAI.GetProvider:input_type -> go_sapaude_dogai.GetProviderReq
	8,  // 6: go_sapaude_dogai.GoSapaudeDogAI.DeleteProviders:input_type -> go_sapaude_dogai.DeleteProvidersReq
	9,  // 7: go_sapaude_dogai.GoSapaudeDogAI.GetProviderSupportModels:input_type -> go_sapaude_dogai.GetProviderSupportModelsReq
	0,  // 8: go_sapaude_dogai.GoSapaudeDogAI.GetAvailableModels:input_type -> go_sapaude_dogai.GetAvailableModelsReq
	10, // 9: go_sapaude_dogai.GoSapaudeDogAI.GetGeneralSettings:output_type -> go_sapaude_dogai.GetGeneralSettingsRsp
	11, // 10: go_sapaude_dogai.GoSapaudeDogAI.SaveGeneralSettings:output_type -> go_sapaude_dogai.SaveGeneralSettingsRsp
	12, // 11: go_sapaude_dogai.GoSapaudeDogAI.SaveProvider:output_type -> go_sapaude_dogai.SaveProviderRsp
	13, // 12: go_sapaude_dogai.GoSapaudeDogAI.UpdateProvider:output_type -> go_sapaude_dogai.UpdateProviderRsp
	14, // 13: go_sapaude_dogai.GoSapaudeDogAI.GetProviderLists:output_type -> go_sapaude_dogai.GetProviderListsRsp
	15, // 14: go_sapaude_dogai.GoSapaudeDogAI.GetProvider:output_type -> go_sapaude_dogai.GetProviderRsp
	16, // 15: go_sapaude_dogai.GoSapaudeDogAI.DeleteProviders:output_type -> go_sapaude_dogai.DeleteProvidersRsp
	17, // 16: go_sapaude_dogai.GoSapaudeDogAI.GetProviderSupportModels:output_type -> go_sapaude_dogai.GetProviderSupportModelsRsp
	1,  // 17: go_sapaude_dogai.GoSapaudeDogAI.GetAvailableModels:output_type -> go_sapaude_dogai.GetAvailableModelsRsp
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_go_sapaude_dogai_proto_init() }
func file_go_sapaude_dogai_proto_init() {
	if File_go_sapaude_dogai_proto != nil {
		return
	}
	file_settings_proto_init()
	file_provider_proto_init()
	file_agent_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_sapaude_dogai_proto_rawDesc), len(file_go_sapaude_dogai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_sapaude_dogai_proto_goTypes,
		DependencyIndexes: file_go_sapaude_dogai_proto_depIdxs,
		MessageInfos:      file_go_sapaude_dogai_proto_msgTypes,
	}.Build()
	File_go_sapaude_dogai_proto = out.File
	file_go_sapaude_dogai_proto_goTypes = nil
	file_go_sapaude_dogai_proto_depIdxs = nil
}
