// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: provider.proto

package go_sapaude_dogai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ModelCapability 模型能力定义
type ModelCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          bool                   `protobuf:"varint,1,opt,name=chat,proto3" json:"chat,omitempty"`                                     // 支持聊天/对话
	Completion    bool                   `protobuf:"varint,2,opt,name=completion,proto3" json:"completion,omitempty"`                         // 支持文本补全
	Vision        bool                   `protobuf:"varint,3,opt,name=vision,proto3" json:"vision,omitempty"`                                 // 支持图像输入
	FunctionCall  bool                   `protobuf:"varint,4,opt,name=function_call,json=functionCall,proto3" json:"function_call,omitempty"` // 支持函数/工具调用
	Embedding     bool                   `protobuf:"varint,5,opt,name=embedding,proto3" json:"embedding,omitempty"`                           // 支持嵌入
	Streaming     bool                   `protobuf:"varint,6,opt,name=streaming,proto3" json:"streaming,omitempty"`                           // 支持流式输出
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelCapability) Reset() {
	*x = ModelCapability{}
	mi := &file_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelCapability) ProtoMessage() {}

func (x *ModelCapability) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelCapability.ProtoReflect.Descriptor instead.
func (*ModelCapability) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{0}
}

func (x *ModelCapability) GetChat() bool {
	if x != nil {
		return x.Chat
	}
	return false
}

func (x *ModelCapability) GetCompletion() bool {
	if x != nil {
		return x.Completion
	}
	return false
}

func (x *ModelCapability) GetVision() bool {
	if x != nil {
		return x.Vision
	}
	return false
}

func (x *ModelCapability) GetFunctionCall() bool {
	if x != nil {
		return x.FunctionCall
	}
	return false
}

func (x *ModelCapability) GetEmbedding() bool {
	if x != nil {
		return x.Embedding
	}
	return false
}

func (x *ModelCapability) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

// ModelMetadata 模型元数据
type ModelMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContextWindow   int32                  `protobuf:"varint,1,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`         // Token上下文窗口大小
	MaxOutputTokens int32                  `protobuf:"varint,2,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"` // 最大输出token数
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                                           // 模型版本
	Family          string                 `protobuf:"bytes,4,opt,name=family,proto3" json:"family,omitempty"`                                             // 模型家族
	SupportsVision  bool                   `protobuf:"varint,5,opt,name=supports_vision,json=supportsVision,proto3" json:"supports_vision,omitempty"`      // 是否支持视觉
	SupportsTools   bool                   `protobuf:"varint,6,opt,name=supports_tools,json=supportsTools,proto3" json:"supports_tools,omitempty"`         // 是否支持工具
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ModelMetadata) Reset() {
	*x = ModelMetadata{}
	mi := &file_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelMetadata) ProtoMessage() {}

func (x *ModelMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelMetadata.ProtoReflect.Descriptor instead.
func (*ModelMetadata) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ModelMetadata) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *ModelMetadata) GetMaxOutputTokens() int32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *ModelMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModelMetadata) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *ModelMetadata) GetSupportsVision() bool {
	if x != nil {
		return x.SupportsVision
	}
	return false
}

func (x *ModelMetadata) GetSupportsTools() bool {
	if x != nil {
		return x.SupportsTools
	}
	return false
}

// ProviderModel Provider支持的模型
type ProviderModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                          // 主键ID
	ProviderId    string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`         // Provider唯一标识
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`                  // 模型ID
	ModelName     string                 `protobuf:"bytes,4,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`            // 模型名称
	ModelType     string                 `protobuf:"bytes,5,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`            // 模型类型(chat/embedding/vision)
	ReleaseTime   string                 `protobuf:"bytes,6,opt,name=release_time,json=releaseTime,proto3" json:"release_time,omitempty"`      // 模型发布时间
	ModelDesc     string                 `protobuf:"bytes,7,opt,name=model_desc,json=modelDesc,proto3" json:"model_desc,omitempty"`            // 模型描述
	Capabilities  *ModelCapability       `protobuf:"bytes,8,opt,name=capabilities,proto3" json:"capabilities,omitempty"`                       // 模型能力
	Metadata      *ModelMetadata         `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`                               // 模型元数据
	IsActive      bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`             // 模型是否可用
	IsDeprecated  bool                   `protobuf:"varint,11,opt,name=is_deprecated,json=isDeprecated,proto3" json:"is_deprecated,omitempty"` // 模型是否已废弃
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`           // 创建时间
	UpdatedAt     string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`           // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderModel) Reset() {
	*x = ProviderModel{}
	mi := &file_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderModel) ProtoMessage() {}

func (x *ProviderModel) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderModel.ProtoReflect.Descriptor instead.
func (*ProviderModel) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderModel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProviderModel) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ProviderModel) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ProviderModel) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ProviderModel) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ProviderModel) GetReleaseTime() string {
	if x != nil {
		return x.ReleaseTime
	}
	return ""
}

func (x *ProviderModel) GetModelDesc() string {
	if x != nil {
		return x.ModelDesc
	}
	return ""
}

func (x *ProviderModel) GetCapabilities() *ModelCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ProviderModel) GetMetadata() *ModelMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProviderModel) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ProviderModel) GetIsDeprecated() bool {
	if x != nil {
		return x.IsDeprecated
	}
	return false
}

func (x *ProviderModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProviderModel) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Provider AI提供商配置
type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // 主键ID
	ProviderId    string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`       // Provider唯一标识
	ProviderName  string                 `protobuf:"bytes,3,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"` // Provider名称
	ApiEndpoint   string                 `protobuf:"bytes,4,opt,name=api_endpoint,json=apiEndpoint,proto3" json:"api_endpoint,omitempty"`    // API端点地址
	ApiKey        string                 `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`                   // API密钥
	Models        []*ProviderModel       `protobuf:"bytes,6,rep,name=models,proto3" json:"models,omitempty"`                                 // 可用模型列表
	IsAvailable   bool                   `protobuf:"varint,7,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`   // API是否可用
	IsDisabled    bool                   `protobuf:"varint,8,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"`      // 是否已禁用
	ProxyUrl      string                 `protobuf:"bytes,9,opt,name=proxy_url,json=proxyUrl,proto3" json:"proxy_url,omitempty"`             // 代理URL
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`         // 创建时间
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`         // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{3}
}

func (x *Provider) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Provider) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *Provider) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *Provider) GetApiEndpoint() string {
	if x != nil {
		return x.ApiEndpoint
	}
	return ""
}

func (x *Provider) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Provider) GetModels() []*ProviderModel {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *Provider) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *Provider) GetIsDisabled() bool {
	if x != nil {
		return x.IsDisabled
	}
	return false
}

func (x *Provider) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

func (x *Provider) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Provider) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// CondProvider 查询Provider的条件
type CondProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // Provider唯一标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CondProvider) Reset() {
	*x = CondProvider{}
	mi := &file_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CondProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CondProvider) ProtoMessage() {}

func (x *CondProvider) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CondProvider.ProtoReflect.Descriptor instead.
func (*CondProvider) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{4}
}

func (x *CondProvider) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

// SaveProviderReq 保存Provider请求
type SaveProviderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveProviderReq) Reset() {
	*x = SaveProviderReq{}
	mi := &file_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveProviderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveProviderReq) ProtoMessage() {}

func (x *SaveProviderReq) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveProviderReq.ProtoReflect.Descriptor instead.
func (*SaveProviderReq) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{5}
}

func (x *SaveProviderReq) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

// SaveProviderRsp 保存Provider响应
type SaveProviderRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveProviderRsp) Reset() {
	*x = SaveProviderRsp{}
	mi := &file_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveProviderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveProviderRsp) ProtoMessage() {}

func (x *SaveProviderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveProviderRsp.ProtoReflect.Descriptor instead.
func (*SaveProviderRsp) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{6}
}

// UpdateProviderReq 更新Provider请求
type UpdateProviderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // Provider唯一标识
	Provider      *Provider              `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`                       // 更新的Provider信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProviderReq) Reset() {
	*x = UpdateProviderReq{}
	mi := &file_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProviderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProviderReq) ProtoMessage() {}

func (x *UpdateProviderReq) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProviderReq.ProtoReflect.Descriptor instead.
func (*UpdateProviderReq) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProviderReq) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *UpdateProviderReq) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

// UpdateProviderRsp 更新Provider响应
type UpdateProviderRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProviderRsp) Reset() {
	*x = UpdateProviderRsp{}
	mi := &file_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProviderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProviderRsp) ProtoMessage() {}

func (x *UpdateProviderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProviderRsp.ProtoReflect.Descriptor instead.
func (*UpdateProviderRsp) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{8}
}

// GetProviderListsReq 查询Provider列表请求
type GetProviderListsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Condition     *CondProvider          `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"` // 查询条件(可选)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderListsReq) Reset() {
	*x = GetProviderListsReq{}
	mi := &file_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderListsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderListsReq) ProtoMessage() {}

func (x *GetProviderListsReq) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderListsReq.ProtoReflect.Descriptor instead.
func (*GetProviderListsReq) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{9}
}

func (x *GetProviderListsReq) GetCondition() *CondProvider {
	if x != nil {
		return x.Condition
	}
	return nil
}

// GetProviderListsRsp 查询Provider列表响应
type GetProviderListsRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*Provider            `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderListsRsp) Reset() {
	*x = GetProviderListsRsp{}
	mi := &file_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderListsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderListsRsp) ProtoMessage() {}

func (x *GetProviderListsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderListsRsp.ProtoReflect.Descriptor instead.
func (*GetProviderListsRsp) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{10}
}

func (x *GetProviderListsRsp) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

// GetProviderReq 获取指定Provider请求
type GetProviderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // Provider唯一标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderReq) Reset() {
	*x = GetProviderReq{}
	mi := &file_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderReq) ProtoMessage() {}

func (x *GetProviderReq) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderReq.ProtoReflect.Descriptor instead.
func (*GetProviderReq) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{11}
}

func (x *GetProviderReq) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

// GetProviderRsp 获取指定Provider响应
type GetProviderRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderRsp) Reset() {
	*x = GetProviderRsp{}
	mi := &file_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderRsp) ProtoMessage() {}

func (x *GetProviderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderRsp.ProtoReflect.Descriptor instead.
func (*GetProviderRsp) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{12}
}

func (x *GetProviderRsp) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

// DeleteProvidersReq 删除Providers请求
type DeleteProvidersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderIds   []string               `protobuf:"bytes,1,rep,name=provider_ids,json=providerIds,proto3" json:"provider_ids,omitempty"` // Provider唯一标识列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProvidersReq) Reset() {
	*x = DeleteProvidersReq{}
	mi := &file_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProvidersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProvidersReq) ProtoMessage() {}

func (x *DeleteProvidersReq) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProvidersReq.ProtoReflect.Descriptor instead.
func (*DeleteProvidersReq) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteProvidersReq) GetProviderIds() []string {
	if x != nil {
		return x.ProviderIds
	}
	return nil
}

// DeleteProvidersRsp 删除Providers响应
type DeleteProvidersRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProvidersRsp) Reset() {
	*x = DeleteProvidersRsp{}
	mi := &file_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProvidersRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProvidersRsp) ProtoMessage() {}

func (x *DeleteProvidersRsp) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProvidersRsp.ProtoReflect.Descriptor instead.
func (*DeleteProvidersRsp) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{14}
}

// GetProviderSupportModelsReq 获取Provider支持的模型列表请求
type GetProviderSupportModelsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // Provider唯一标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderSupportModelsReq) Reset() {
	*x = GetProviderSupportModelsReq{}
	mi := &file_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderSupportModelsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderSupportModelsReq) ProtoMessage() {}

func (x *GetProviderSupportModelsReq) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderSupportModelsReq.ProtoReflect.Descriptor instead.
func (*GetProviderSupportModelsReq) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{15}
}

func (x *GetProviderSupportModelsReq) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

// GetProviderSupportModelsRsp 获取Provider支持的模型列表响应
type GetProviderSupportModelsRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ProviderModel       `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderSupportModelsRsp) Reset() {
	*x = GetProviderSupportModelsRsp{}
	mi := &file_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderSupportModelsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderSupportModelsRsp) ProtoMessage() {}

func (x *GetProviderSupportModelsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderSupportModelsRsp.ProtoReflect.Descriptor instead.
func (*GetProviderSupportModelsRsp) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{16}
}

func (x *GetProviderSupportModelsRsp) GetModels() []*ProviderModel {
	if x != nil {
		return x.Models
	}
	return nil
}

var File_provider_proto protoreflect.FileDescriptor

const file_provider_proto_rawDesc = "" +
	"\n" +
	"\x0eprovider.proto\x12\x10go_sapaude_dogai\"\xbe\x01\n" +
	"\x0fModelCapability\x12\x12\n" +
	"\x04chat\x18\x01 \x01(\bR\x04chat\x12\x1e\n" +
	"\n" +
	"completion\x18\x02 \x01(\bR\n" +
	"completion\x12\x16\n" +
	"\x06vision\x18\x03 \x01(\bR\x06vision\x12#\n" +
	"\rfunction_call\x18\x04 \x01(\bR\ffunctionCall\x12\x1c\n" +
	"\tembedding\x18\x05 \x01(\bR\tembedding\x12\x1c\n" +
	"\tstreaming\x18\x06 \x01(\bR\tstreaming\"\xe4\x01\n" +
	"\rModelMetadata\x12%\n" +
	"\x0econtext_window\x18\x01 \x01(\x05R\rcontextWindow\x12*\n" +
	"\x11max_output_tokens\x18\x02 \x01(\x05R\x0fmaxOutputTokens\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06family\x18\x04 \x01(\tR\x06family\x12'\n" +
	"\x0fsupports_vision\x18\x05 \x01(\bR\x0esupportsVision\x12%\n" +
	"\x0esupports_tools\x18\x06 \x01(\bR\rsupportsTools\"\xdf\x03\n" +
	"\rProviderModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x04 \x01(\tR\tmodelName\x12\x1d\n" +
	"\n" +
	"model_type\x18\x05 \x01(\tR\tmodelType\x12!\n" +
	"\frelease_time\x18\x06 \x01(\tR\vreleaseTime\x12\x1d\n" +
	"\n" +
	"model_desc\x18\a \x01(\tR\tmodelDesc\x12E\n" +
	"\fcapabilities\x18\b \x01(\v2!.go_sapaude_dogai.ModelCapabilityR\fcapabilities\x12;\n" +
	"\bmetadata\x18\t \x01(\v2\x1f.go_sapaude_dogai.ModelMetadataR\bmetadata\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x12#\n" +
	"\ris_deprecated\x18\v \x01(\bR\fisDeprecated\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\"\xf4\x02\n" +
	"\bProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12#\n" +
	"\rprovider_name\x18\x03 \x01(\tR\fproviderName\x12!\n" +
	"\fapi_endpoint\x18\x04 \x01(\tR\vapiEndpoint\x12\x17\n" +
	"\aapi_key\x18\x05 \x01(\tR\x06apiKey\x127\n" +
	"\x06models\x18\x06 \x03(\v2\x1f.go_sapaude_dogai.ProviderModelR\x06models\x12!\n" +
	"\fis_available\x18\a \x01(\bR\visAvailable\x12\x1f\n" +
	"\vis_disabled\x18\b \x01(\bR\n" +
	"isDisabled\x12\x1b\n" +
	"\tproxy_url\x18\t \x01(\tR\bproxyUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"/\n" +
	"\fCondProvider\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"I\n" +
	"\x0fSaveProviderReq\x126\n" +
	"\bprovider\x18\x01 \x01(\v2\x1a.go_sapaude_dogai.ProviderR\bprovider\"\x11\n" +
	"\x0fSaveProviderRsp\"l\n" +
	"\x11UpdateProviderReq\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x126\n" +
	"\bprovider\x18\x02 \x01(\v2\x1a.go_sapaude_dogai.ProviderR\bprovider\"\x13\n" +
	"\x11UpdateProviderRsp\"S\n" +
	"\x13GetProviderListsReq\x12<\n" +
	"\tcondition\x18\x01 \x01(\v2\x1e.go_sapaude_dogai.CondProviderR\tcondition\"O\n" +
	"\x13GetProviderListsRsp\x128\n" +
	"\tproviders\x18\x01 \x03(\v2\x1a.go_sapaude_dogai.ProviderR\tproviders\"1\n" +
	"\x0eGetProviderReq\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"H\n" +
	"\x0eGetProviderRsp\x126\n" +
	"\bprovider\x18\x01 \x01(\v2\x1a.go_sapaude_dogai.ProviderR\bprovider\"7\n" +
	"\x12DeleteProvidersReq\x12!\n" +
	"\fprovider_ids\x18\x01 \x03(\tR\vproviderIds\"\x14\n" +
	"\x12DeleteProvidersRsp\">\n" +
	"\x1bGetProviderSupportModelsReq\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"V\n" +
	"\x1bGetProviderSupportModelsRsp\x127\n" +
	"\x06models\x18\x01 \x03(\v2\x1f.go_sapaude_dogai.ProviderModelR\x06modelsB1Z/github.com/sapaude/protocol/ai/go_sapaude_dogaib\x06proto3"

var (
	file_provider_proto_rawDescOnce sync.Once
	file_provider_proto_rawDescData []byte
)

func file_provider_proto_rawDescGZIP() []byte {
	file_provider_proto_rawDescOnce.Do(func() {
		file_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)))
	})
	return file_provider_proto_rawDescData
}

var file_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_provider_proto_goTypes = []any{
	(*ModelCapability)(nil),             // 0: go_sapaude_dogai.ModelCapability
	(*ModelMetadata)(nil),               // 1: go_sapaude_dogai.ModelMetadata
	(*ProviderModel)(nil),               // 2: go_sapaude_dogai.ProviderModel
	(*Provider)(nil),                    // 3: go_sapaude_dogai.Provider
	(*CondProvider)(nil),                // 4: go_sapaude_dogai.CondProvider
	(*SaveProviderReq)(nil),             // 5: go_sapaude_dogai.SaveProviderReq
	(*SaveProviderRsp)(nil),             // 6: go_sapaude_dogai.SaveProviderRsp
	(*UpdateProviderReq)(nil),           // 7: go_sapaude_dogai.UpdateProviderReq
	(*UpdateProviderRsp)(nil),           // 8: go_sapaude_dogai.UpdateProviderRsp
	(*GetProviderListsReq)(nil),         // 9: go_sapaude_dogai.GetProviderListsReq
	(*GetProviderListsRsp)(nil),         // 10: go_sapaude_dogai.GetProviderListsRsp
	(*GetProviderReq)(nil),              // 11: go_sapaude_dogai.GetProviderReq
	(*GetProviderRsp)(nil),              // 12: go_sapaude_dogai.GetProviderRsp
	(*DeleteProvidersReq)(nil),          // 13: go_sapaude_dogai.DeleteProvidersReq
	(*DeleteProvidersRsp)(nil),          // 14: go_sapaude_dogai.DeleteProvidersRsp
	(*GetProviderSupportModelsReq)(nil), // 15: go_sapaude_dogai.GetProviderSupportModelsReq
	(*GetProviderSupportModelsRsp)(nil), // 16: go_sapaude_dogai.GetProviderSupportModelsRsp
}
var file_provider_proto_depIdxs = []int32{
	0, // 0: go_sapaude_dogai.ProviderModel.capabilities:type_name -> go_sapaude_dogai.ModelCapability
	1, // 1: go_sapaude_dogai.ProviderModel.metadata:type_name -> go_sapaude_dogai.ModelMetadata
	2, // 2: go_sapaude_dogai.Provider.models:type_name -> go_sapaude_dogai.ProviderModel
	3, // 3: go_sapaude_dogai.SaveProviderReq.provider:type_name -> go_sapaude_dogai.Provider
	3, // 4: go_sapaude_dogai.UpdateProviderReq.provider:type_name -> go_sapaude_dogai.Provider
	4, // 5: go_sapaude_dogai.GetProviderListsReq.condition:type_name -> go_sapaude_dogai.CondProvider
	3, // 6: go_sapaude_dogai.GetProviderListsRsp.providers:type_name -> go_sapaude_dogai.Provider
	3, // 7: go_sapaude_dogai.GetProviderRsp.provider:type_name -> go_sapaude_dogai.Provider
	2, // 8: go_sapaude_dogai.GetProviderSupportModelsRsp.models:type_name -> go_sapaude_dogai.ProviderModel
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_provider_proto_init() }
func file_provider_proto_init() {
	if File_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_provider_proto_goTypes,
		DependencyIndexes: file_provider_proto_depIdxs,
		MessageInfos:      file_provider_proto_msgTypes,
	}.Build()
	File_provider_proto = out.File
	file_provider_proto_goTypes = nil
	file_provider_proto_depIdxs = nil
}
