// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: settings.proto

package go_sapaude_dogai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GeneralSetting 通用应用配置
type GeneralSetting struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Theme            string                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`                                                  // 主题(light/dark/auto)
	Language         string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`                                            // 语言(zh-CN/en-US等)
	ChatWindowWidth  int32                  `protobuf:"varint,3,opt,name=chat_window_width,json=chatWindowWidth,proto3" json:"chat_window_width,omitempty"`    // 聊天窗口宽度
	ChatWindowHeight int32                  `protobuf:"varint,4,opt,name=chat_window_height,json=chatWindowHeight,proto3" json:"chat_window_height,omitempty"` // 聊天窗口高度
	AlwaysOnTop      bool                   `protobuf:"varint,5,opt,name=always_on_top,json=alwaysOnTop,proto3" json:"always_on_top,omitempty"`                // 是否窗口置顶
	ProxyUrl         string                 `protobuf:"bytes,6,opt,name=proxy_url,json=proxyUrl,proto3" json:"proxy_url,omitempty"`                            // 代理URL
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GeneralSetting) Reset() {
	*x = GeneralSetting{}
	mi := &file_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralSetting) ProtoMessage() {}

func (x *GeneralSetting) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralSetting.ProtoReflect.Descriptor instead.
func (*GeneralSetting) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{0}
}

func (x *GeneralSetting) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *GeneralSetting) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GeneralSetting) GetChatWindowWidth() int32 {
	if x != nil {
		return x.ChatWindowWidth
	}
	return 0
}

func (x *GeneralSetting) GetChatWindowHeight() int32 {
	if x != nil {
		return x.ChatWindowHeight
	}
	return 0
}

func (x *GeneralSetting) GetAlwaysOnTop() bool {
	if x != nil {
		return x.AlwaysOnTop
	}
	return false
}

func (x *GeneralSetting) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

// 兼容旧命名的请求响应消息(保持向后兼容)
type GetGeneralSettingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGeneralSettingsReq) Reset() {
	*x = GetGeneralSettingsReq{}
	mi := &file_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGeneralSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeneralSettingsReq) ProtoMessage() {}

func (x *GetGeneralSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeneralSettingsReq.ProtoReflect.Descriptor instead.
func (*GetGeneralSettingsReq) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{1}
}

type GetGeneralSettingsRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *GeneralSetting        `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGeneralSettingsRsp) Reset() {
	*x = GetGeneralSettingsRsp{}
	mi := &file_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGeneralSettingsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeneralSettingsRsp) ProtoMessage() {}

func (x *GetGeneralSettingsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeneralSettingsRsp.ProtoReflect.Descriptor instead.
func (*GetGeneralSettingsRsp) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{2}
}

func (x *GetGeneralSettingsRsp) GetSettings() *GeneralSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SaveGeneralSettingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *GeneralSetting        `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveGeneralSettingsReq) Reset() {
	*x = SaveGeneralSettingsReq{}
	mi := &file_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveGeneralSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGeneralSettingsReq) ProtoMessage() {}

func (x *SaveGeneralSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGeneralSettingsReq.ProtoReflect.Descriptor instead.
func (*SaveGeneralSettingsReq) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{3}
}

func (x *SaveGeneralSettingsReq) GetSettings() *GeneralSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SaveGeneralSettingsRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveGeneralSettingsRsp) Reset() {
	*x = SaveGeneralSettingsRsp{}
	mi := &file_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveGeneralSettingsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGeneralSettingsRsp) ProtoMessage() {}

func (x *SaveGeneralSettingsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGeneralSettingsRsp.ProtoReflect.Descriptor instead.
func (*SaveGeneralSettingsRsp) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{4}
}

var File_settings_proto protoreflect.FileDescriptor

const file_settings_proto_rawDesc = "" +
	"\n" +
	"\x0esettings.proto\x12\x10go_sapaude_dogai\"\xdd\x01\n" +
	"\x0eGeneralSetting\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12*\n" +
	"\x11chat_window_width\x18\x03 \x01(\x05R\x0fchatWindowWidth\x12,\n" +
	"\x12chat_window_height\x18\x04 \x01(\x05R\x10chatWindowHeight\x12\"\n" +
	"\ralways_on_top\x18\x05 \x01(\bR\valwaysOnTop\x12\x1b\n" +
	"\tproxy_url\x18\x06 \x01(\tR\bproxyUrl\"\x17\n" +
	"\x15GetGeneralSettingsReq\"U\n" +
	"\x15GetGeneralSettingsRsp\x12<\n" +
	"\bsettings\x18\x01 \x01(\v2 .go_sapaude_dogai.GeneralSettingR\bsettings\"V\n" +
	"\x16SaveGeneralSettingsReq\x12<\n" +
	"\bsettings\x18\x01 \x01(\v2 .go_sapaude_dogai.GeneralSettingR\bsettings\"\x18\n" +
	"\x16SaveGeneralSettingsRspB1Z/github.com/sapaude/protocol/ai/go_sapaude_dogaib\x06proto3"

var (
	file_settings_proto_rawDescOnce sync.Once
	file_settings_proto_rawDescData []byte
)

func file_settings_proto_rawDescGZIP() []byte {
	file_settings_proto_rawDescOnce.Do(func() {
		file_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settings_proto_rawDesc), len(file_settings_proto_rawDesc)))
	})
	return file_settings_proto_rawDescData
}

var file_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_settings_proto_goTypes = []any{
	(*GeneralSetting)(nil),         // 0: go_sapaude_dogai.GeneralSetting
	(*GetGeneralSettingsReq)(nil),  // 1: go_sapaude_dogai.GetGeneralSettingsReq
	(*GetGeneralSettingsRsp)(nil),  // 2: go_sapaude_dogai.GetGeneralSettingsRsp
	(*SaveGeneralSettingsReq)(nil), // 3: go_sapaude_dogai.SaveGeneralSettingsReq
	(*SaveGeneralSettingsRsp)(nil), // 4: go_sapaude_dogai.SaveGeneralSettingsRsp
}
var file_settings_proto_depIdxs = []int32{
	0, // 0: go_sapaude_dogai.GetGeneralSettingsRsp.settings:type_name -> go_sapaude_dogai.GeneralSetting
	0, // 1: go_sapaude_dogai.SaveGeneralSettingsReq.settings:type_name -> go_sapaude_dogai.GeneralSetting
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_settings_proto_init() }
func file_settings_proto_init() {
	if File_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settings_proto_rawDesc), len(file_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_settings_proto_goTypes,
		DependencyIndexes: file_settings_proto_depIdxs,
		MessageInfos:      file_settings_proto_msgTypes,
	}.Build()
	File_settings_proto = out.File
	file_settings_proto_goTypes = nil
	file_settings_proto_depIdxs = nil
}
