// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: go_sapaude_backend_admin.proto

package go_sapaude_backend_admin

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户信息
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Uname         string                 `protobuf:"bytes,2,opt,name=uname,proto3" json:"uname,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_go_sapaude_backend_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_go_sapaude_backend_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_go_sapaude_backend_admin_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *User) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 注册用户请求
type RegisterUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uname         string                 `protobuf:"bytes,1,opt,name=uname,proto3" json:"uname,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserReq) Reset() {
	*x = RegisterUserReq{}
	mi := &file_go_sapaude_backend_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserReq) ProtoMessage() {}

func (x *RegisterUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_go_sapaude_backend_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserReq.ProtoReflect.Descriptor instead.
func (*RegisterUserReq) Descriptor() ([]byte, []int) {
	return file_go_sapaude_backend_admin_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserReq) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

func (x *RegisterUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 注册用户响应
type RegisterUserRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRsp) Reset() {
	*x = RegisterUserRsp{}
	mi := &file_go_sapaude_backend_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRsp) ProtoMessage() {}

func (x *RegisterUserRsp) ProtoReflect() protoreflect.Message {
	mi := &file_go_sapaude_backend_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRsp.ProtoReflect.Descriptor instead.
func (*RegisterUserRsp) Descriptor() ([]byte, []int) {
	return file_go_sapaude_backend_admin_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterUserRsp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// 获取用户请求
type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_go_sapaude_backend_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_go_sapaude_backend_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_go_sapaude_backend_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// 获取用户响应
type GetUserResponseRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponseRsp) Reset() {
	*x = GetUserResponseRsp{}
	mi := &file_go_sapaude_backend_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponseRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponseRsp) ProtoMessage() {}

func (x *GetUserResponseRsp) ProtoReflect() protoreflect.Message {
	mi := &file_go_sapaude_backend_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponseRsp.ProtoReflect.Descriptor instead.
func (*GetUserResponseRsp) Descriptor() ([]byte, []int) {
	return file_go_sapaude_backend_admin_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserResponseRsp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uname         string                 `protobuf:"bytes,1,opt,name=uname,proto3" json:"uname,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_go_sapaude_backend_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_go_sapaude_backend_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_go_sapaude_backend_admin_proto_rawDescGZIP(), []int{5}
}

func (x *LoginReq) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

func (x *LoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRsp) Reset() {
	*x = LoginRsp{}
	mi := &file_go_sapaude_backend_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRsp) ProtoMessage() {}

func (x *LoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_go_sapaude_backend_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRsp.ProtoReflect.Descriptor instead.
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return file_go_sapaude_backend_admin_proto_rawDescGZIP(), []int{6}
}

func (x *LoginRsp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_go_sapaude_backend_admin_proto protoreflect.FileDescriptor

const file_go_sapaude_backend_admin_proto_rawDesc = "" +
	"\n" +
	"\x1ego_sapaude_backend_admin.proto\x12\x18go_sapaude_backend_admin\x1a\x1cgoogle/api/annotations.proto\"c\n" +
	"\x04User\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x14\n" +
	"\x05uname\x18\x02 \x01(\tR\x05uname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"Y\n" +
	"\x0fRegisterUserReq\x12\x14\n" +
	"\x05uname\x18\x01 \x01(\tR\x05uname\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"E\n" +
	"\x0fRegisterUserRsp\x122\n" +
	"\x04user\x18\x01 \x01(\v2\x1e.go_sapaude_backend_admin.UserR\x04user\"\x1e\n" +
	"\n" +
	"GetUserReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"H\n" +
	"\x12GetUserResponseRsp\x122\n" +
	"\x04user\x18\x01 \x01(\v2\x1e.go_sapaude_backend_admin.UserR\x04user\"R\n" +
	"\bLoginReq\x12\x14\n" +
	"\x05uname\x18\x01 \x01(\tR\x05uname\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\" \n" +
	"\bLoginRsp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xf9\x02\n" +
	"\x15GoSapaudeBackendAdmin\x12h\n" +
	"\x05Login\x12\".go_sapaude_backend_admin.LoginReq\x1a\".go_sapaude_backend_admin.LoginRsp\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/users/login\x12\x80\x01\n" +
	"\fRegisterUser\x12).go_sapaude_backend_admin.RegisterUserReq\x1a).go_sapaude_backend_admin.RegisterUserRsp\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/users/register\x12s\n" +
	"\aGetUser\x12$.go_sapaude_backend_admin.GetUserReq\x1a,.go_sapaude_backend_admin.GetUserResponseRsp\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/users/{uid}B=Z;github.com/sapaude/protocol/devops/go_sapaude_backend_adminb\x06proto3"

var (
	file_go_sapaude_backend_admin_proto_rawDescOnce sync.Once
	file_go_sapaude_backend_admin_proto_rawDescData []byte
)

func file_go_sapaude_backend_admin_proto_rawDescGZIP() []byte {
	file_go_sapaude_backend_admin_proto_rawDescOnce.Do(func() {
		file_go_sapaude_backend_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_sapaude_backend_admin_proto_rawDesc), len(file_go_sapaude_backend_admin_proto_rawDesc)))
	})
	return file_go_sapaude_backend_admin_proto_rawDescData
}

var file_go_sapaude_backend_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_go_sapaude_backend_admin_proto_goTypes = []any{
	(*User)(nil),               // 0: go_sapaude_backend_admin.User
	(*RegisterUserReq)(nil),    // 1: go_sapaude_backend_admin.RegisterUserReq
	(*RegisterUserRsp)(nil),    // 2: go_sapaude_backend_admin.RegisterUserRsp
	(*GetUserReq)(nil),         // 3: go_sapaude_backend_admin.GetUserReq
	(*GetUserResponseRsp)(nil), // 4: go_sapaude_backend_admin.GetUserResponseRsp
	(*LoginReq)(nil),           // 5: go_sapaude_backend_admin.LoginReq
	(*LoginRsp)(nil),           // 6: go_sapaude_backend_admin.LoginRsp
}
var file_go_sapaude_backend_admin_proto_depIdxs = []int32{
	0, // 0: go_sapaude_backend_admin.RegisterUserRsp.user:type_name -> go_sapaude_backend_admin.User
	0, // 1: go_sapaude_backend_admin.GetUserResponseRsp.user:type_name -> go_sapaude_backend_admin.User
	5, // 2: go_sapaude_backend_admin.GoSapaudeBackendAdmin.Login:input_type -> go_sapaude_backend_admin.LoginReq
	1, // 3: go_sapaude_backend_admin.GoSapaudeBackendAdmin.RegisterUser:input_type -> go_sapaude_backend_admin.RegisterUserReq
	3, // 4: go_sapaude_backend_admin.GoSapaudeBackendAdmin.GetUser:input_type -> go_sapaude_backend_admin.GetUserReq
	6, // 5: go_sapaude_backend_admin.GoSapaudeBackendAdmin.Login:output_type -> go_sapaude_backend_admin.LoginRsp
	2, // 6: go_sapaude_backend_admin.GoSapaudeBackendAdmin.RegisterUser:output_type -> go_sapaude_backend_admin.RegisterUserRsp
	4, // 7: go_sapaude_backend_admin.GoSapaudeBackendAdmin.GetUser:output_type -> go_sapaude_backend_admin.GetUserResponseRsp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_go_sapaude_backend_admin_proto_init() }
func file_go_sapaude_backend_admin_proto_init() {
	if File_go_sapaude_backend_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_sapaude_backend_admin_proto_rawDesc), len(file_go_sapaude_backend_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_sapaude_backend_admin_proto_goTypes,
		DependencyIndexes: file_go_sapaude_backend_admin_proto_depIdxs,
		MessageInfos:      file_go_sapaude_backend_admin_proto_msgTypes,
	}.Build()
	File_go_sapaude_backend_admin_proto = out.File
	file_go_sapaude_backend_admin_proto_goTypes = nil
	file_go_sapaude_backend_admin_proto_depIdxs = nil
}
